### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by storm134** [crunchy-labs/crunchyroll-go#5]
is there any instruction on how to use. i installed go but anytime i run any file i get "package command-line-arguments is not a main package" not sure what i am missing. any help or push in right direction would be appreciated

**Comment by bytedream** [comment]
The client got renamed and moved to its own repository, _[crunchy-cli](https://github.com/crunchy-labs/crunchy-cli)_.
I'll add a notice to this in the README (I always thought such a notice were already there).

**Comment by storm134** [comment]
thanks, will give it a try. i see there is an exe anything special need to use that?

**Comment by bytedream** [comment]
Not directly.
The default file format for downloaded videos is [.ts](https://en.wikipedia.org/wiki/MPEG_transport_stream). If you want to store it in any other format (e.g. mp4), you need [ffmpeg](https://ffmpeg.org/).

**Comment by storm134** [comment]
Thanks fine i was using multi-downloader-nx-master (stopped working this week and seems project been dropped. get 404 page from github now). I was keeping the ts files then shrinking them using ffmpeg and converting them using ffmpeg. so i don't have an issue with ts files
